# Generated by Django 2.0.3 on 2018-04-15 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocabulary', '0007_vocabulary_force_unique_nodeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(unique=True, verbose_name='URI / Unique Resource ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.Concept')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.Record')),
            ],
        ),
    ]
