# Generated by Django 4.2.11 on 2025-01-20 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vocabulary", "0001_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relation",
            name="object_value",
            field=models.TextField(blank=True, default="", verbose_name="Object value"),
        ),
        migrations.AlterField(
            model_name="relation",
            name="object_value_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("char", "One or more characters"),
                    ("bool", "Yes or No"),
                    ("json", "Valid JSON"),
                    ("int", "Integer number"),
                    ("dec", "Decimal number"),
                ],
                default="",
                max_length=4,
                verbose_name="Object type",
            ),
        ),
        migrations.AlterField(
            model_name="relation",
            name="predicate",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predicate",
                to="vocabulary.concept",
            ),
        ),
        migrations.AlterField(
            model_name="vocabulary",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="vocabulary",
            name="source",
            field=models.URLField(blank=True, default=""),
        ),
    ]
