# Generated by Django 2.2.1 on 2019-06-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0009_authority_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
