# Generated by Django 4.2.11 on 2025-01-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocabulary", "0014_vocabulary_predicates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vocabulary",
            name="source",
            field=models.URLField(blank=True, null=True),
        ),
    ]
