INSERT INTO languages (iso, name) VALUES
('af',    'Afrikaans'            ),
('sq',    'Albanian'             ),
('ar',    'Arabic'               ),
('be',    'Belarusian '          ),
('bg',    'Bulgarian'            ),
('ca',    'Catalan'              ),
('zh-cn', 'Chinese (Simplified)' ),
('zh-tw', 'Chinese (Traditional)'),
('hr',    'Croatian'             ),
('cs',    'Czech'                ),
('da',    'Danish'               ),
('nl',    'Dutch'                ),
('en',    'English'              ),
('et',    'Estonian'             ),
('tl',    'Filipino'             ),
('fi',    'Finnish'              ),
('fr',    'French'               ),
('gl',    'Galician'             ),
('de',    'German'               ),
('el',    'Greek'                ),
('ht',    'Haitian Creole'       ),
('iw',    'Hebrew'               ),
('hi',    'Hindi'                ),
('hu',    'Hungarian'            ),
('is',    'Icelandic'            ),
('id',    'Indonesian'           ),
('ga',    'Irish'                ),
('it',    'Italian'              ),
('ja',    'Japanese'             ),
('ko',    'Korean'               ),
('lv',    'Latvian'              ),
('lt',    'Lithuanian'           ),
('mk',    'Macedonian'           ),
('ms',    'Malay'                ),
('mt',    'Maltese'              ),
('no',    'Norwegian'            ),
('fa',    'Persian'              ),
('pl',    'Polish'               ),
('pt',    'Portuguese'           ),
('ro',    'Romanian'             ),
('ru',    'Russian'              ),
('sr',    'Serbian'              ),
('sk',    'Slovak'               ),
('sl',    'Slovenian'            ),
('es',    'Spanish'              ),
('sw',    'Swahili'              ),
('sv',    'Swedish'              ),
('th',    'Thai'                 ),
('tr',    'Turkish'              ),
('uk',    'Ukrainian'            ),
('vi',    'Vietnamese'           ),
('cy',    'Welsh'                ),
('yi',    'Yiddish'              );

REPLACE INTO auth_user SET
    id=1,
    username='admin',
    first_name='Admin',
    last_name=' ',
    email='',
    password='sha1$HlD1jrOkxFgp$34f8e57651c3af4baf4b2eed87cbc6dc428905a8', # admin
    is_staff=1,
    is_active=1,
    is_superuser=1,
    last_login='2000-01-01 00:00:00',
    date_joined='2000-01-01 00:00:00';

UPDATE django_site SET domain='unilexicon.com', name='Unilexicon' WHERE id=1;
