# Generated by Django 2.0.5 on 2018-06-05 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='URL')),
                ('message', models.TextField()),
                ('browser', models.CharField(max_length=500)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('ip', models.CharField(blank=True, max_length=225, verbose_name='IP')),
                ('awesome', models.BooleanField(default=False)),
                ('ignore', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
