# Generated by Django 2.0.4 on 2019-05-29 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocabulary', '0008_allow_longer_node_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='users',
            field=models.ManyToManyField(help_text='Authority can have many users. Vocabulary can have one authority.', to=settings.AUTH_USER_MODEL),
        ),
    ]
