# Generated by Django 2.0.4 on 2019-05-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0009_authority_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authority',
            options={'verbose_name_plural': 'Authorities'},
        ),
        migrations.AddField(
            model_name='authority',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authority',
            name='code',
            field=models.CharField(db_index=True, help_text='Uppercase shorthand, no spaces', max_length=5),
        ),
    ]
