from django.conf.urls import url, patterns, include

urlpatterns = patterns('vocabulary.views',
    url(r'^$',                        'listings', name='listings'),
    url(r'^add$',                     'vocabulary_add', name='add'),
       (r'^autocomplete$',            'autocomplete'),
       (r'^search$',                  'search'),
    url(r'^load-(?P<format>[a-z]+)$', 'load_vocab', name='load'),
    url(r'^(?P<vocab_node_id>[a-z0-9-]+)/$',         'detail', name='vocabulary'),
    url(r'^(?P<vocab_node_id>[a-z0-9-]+)/edit$',     'vocabulary_edit'),
    url(r'^(?P<vocab_node_id>[a-z0-9-]+)/delete$',   'vocabulary_delete'),
    url(r'^(?P<vocab_node_id>[a-z0-9-]+)/json$',     'json'    , name='json'    ),
    url(r'^(?P<vocab_node_id>[a-z0-9-]+)/csv$',      'csv'     , name='csv'     ),
    url(r'^(?P<vocab_node_id>[a-z0-9-]+)/glossary$', 'glossary', name='glossary'),
    url(r'^(?P<vocab_node_id>[a-z0-9-]+)/skos$',     'skos'    , name='skos'    ),
    url(r'^(?P<vocab_node_id>[a-z0-9-]+)/order$',    'ul', {'style': 'order'}, name='order'),
    url(r'^(?P<vocab_node_id>[a-z0-9-]+)/nav$',      'ul', {'style': 'nav'}, name='nav'),
    url(r'^(?P<vocab_node_id>[a-z0-9-]+)/ul$',       'ul', {'style': 'ul'}, name='ul'),
    url(r'^(?P<vocab_node_id>[a-z0-9-]+)/ordering$', 'ordering', name='ordering'),
       (r'^(?P<vocab_node_id>[a-z0-9-]+)/new$',      'concept_new'),
       (r'^(?P<vocab_node_id>[a-z0-9-]+)/(?P<node_id>[A-Za-z0-9-: ]+)/new',    'concept_new'),
       (r'^(?P<vocab_node_id>[a-z0-9-]+)/(?P<node_id>[A-Za-z0-9-: ]+)/edit',   'concept_edit'),
       (r'^(?P<vocab_node_id>[a-z0-9-]+)/(?P<node_id>[A-Za-z0-9-: ]+)/adopt',  'concept_adopt'),
       (r'^(?P<vocab_node_id>[a-z0-9-]+)/(?P<node_id>[A-Za-z0-9-: ]+)/delete', 'concept_delete'),
)