from django.conf.urls import url, patterns, include

urlpatterns = patterns('vocabulary.views',
    url(r'^$',                        'listings', name='listings'),
       (r'^add$',                     'vocabulary_add'),
       (r'^autocomplete$',            'autocomplete'),
       (r'^search$',                  'search'),
       (r'^load-(?P<format>[a-z]+)$', 'load_vocab'),
    url(r'^(?P<vocab_node_id>[a-z0-9-]+)/$',              'detail', name='vocabulary'),
       (r'^(?P<vocab_node_id>[a-z0-9-]+)/edit$',          'vocabulary_edit'),
       (r'^(?P<vocab_node_id>[a-z0-9-]+)/delete$',        'vocabulary_delete'),
       (r'^(?P<vocab_node_id>[a-z0-9-]+)/json$',          'json'),
       (r'^(?P<vocab_node_id>[a-z0-9-]+)/csv$',           'csv'),
       (r'^(?P<vocab_node_id>[a-z0-9-]+)/glossary$',      'glossary'),
       (r'^(?P<vocab_node_id>[a-z0-9-]+)/skos$',          'skos'),
       (r'^(?P<vocab_node_id>[a-z0-9-]+)/meeting$',       'meeting'),
       (r'^(?P<vocab_node_id>[a-z0-9-]+)/megadropdowns$', 'megadropdowns'),
       (r'^(?P<vocab_node_id>[a-z0-9-]+)/order$',         'order'),
       (r'^(?P<vocab_node_id>[a-z0-9-]+)/new$',           'concept_new'),
       (r'^(?P<vocab_node_id>[a-z0-9-]+)/(?P<node_id>[A-Za-z0-9-: ]+)/new',    'concept_new'),
       (r'^(?P<vocab_node_id>[a-z0-9-]+)/(?P<node_id>[A-Za-z0-9-: ]+)/edit',   'concept_edit'),
       (r'^(?P<vocab_node_id>[a-z0-9-]+)/(?P<node_id>[A-Za-z0-9-: ]+)/adopt',  'concept_adopt'),
       (r'^(?P<vocab_node_id>[a-z0-9-]+)/(?P<node_id>[A-Za-z0-9-: ]+)/delete', 'concept_delete'),
)